export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const SAVE_USER = "SAVE_USER";

//________TEAM___________
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAM_SUCCESS = "FETCH_TEAM_SUCCESS";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";

//________BOARD___________
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const FETCH_BOARD_SUCCESS = "FETCH_BOARD_SUCCESS";
export const ADD_BOARD_MEMBER_SUCCESS = "ADD_BOARD_MEMBER_SUCCESS";
export const ADD_BOARD_TEAM_SUCCESS = "ADD_BOARD_TEAM_SUCCESS";

// ________LISTS___________
export const ADD_BOARD_LIST_SUCCESS = "ADD_BOARD_LIST_SUCCESS";
export const FETCH_BOARD_LIST_SUCCESS = "FETCH_BOARD_LIST_SUCCESS";



