export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//________TEAM___________
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
